### ISSUE TITLE
api/server.go uses localhost:8080 instead of api.absam.io

### ISSUE THREAD

**Issue by turicas** [absam-io/absam-cli#1]
Hello!
The lines [12](https://github.com/absam-io/absam-cli/blob/main/api/server.go#L12), [24](https://github.com/absam-io/absam-cli/blob/main/api/server.go#L24), [38](https://github.com/absam-io/absam-cli/blob/main/api/server.go#L38) and [52](https://github.com/absam-io/absam-cli/blob/main/api/server.go#L52) of `api/server.go` will make calls to `localhost:8080` instead of `api.absam.io` (this does not happen on `api/cloud_app.go` and `api/firewall.go`).

**Comment by absamio** [comment]
Hi, the issue has been fixed.
[3d85e9f](https://github.com/absam-io/absam-cli/commit/3d85e9f7ab0090aeb02effbf7887444e12ced1da)
